export enum ErrorCode {
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  NOT_IDENTIFIED = 'NOT_IDENTIFIED',
  INVALID_API_KEY = 'INVALID_API_KEY',
  NETWORK_ERROR = 'NETWORK_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  PROTOCOL_ERROR = 'PROTOCOL_ERROR',
  QUEUE_OVERFLOW = 'QUEUE_OVERFLOW',
  MAX_RETRIES_EXCEEDED = 'MAX_RETRIES_EXCEEDED',
}
